aider: Update layout to use `probeScaleLineEdit` instead of `probeScaleSpinBox` in `PtychoPINNModelParametersView`.
# Aider chat conversation:

USER:
Traceback (most recent call last):
  File "/Users/ollie/anaconda3/envs/ptychodus/bin/ptychodus", line 5, in <module>
    from ptychodus.__main__ import main
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/__main__.py", line 108, in <module>
    sys.exit(main())
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/__main__.py", line 102, in main
    controller = ControllerCore.createInstance(model, view)
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/controller/core.py", line 99, in createInstance
    controller = cls(model, view)
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/controller/core.py", line 67, in __init__
    self._reconstructorParametersController = ReconstructorParametersController.createInstance(
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/controller/reconstructor.py", line 72, in createInstance
    controller._addReconstructor(name)
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/controller/reconstructor.py", line 108, in _addReconstructor
    widget = viewControllerFactory.createViewController(reconstructorName)
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/controller/ptychopinn/factory.py", line 25, in createViewController
    view = PtychoPINNParametersView.createInstance()
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/view/ptychopinn.py", line 149, in createInstance
    view = cls(parent)
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/view/ptychopinn.py", line 144, in __init__
    self.modelParametersView = PtychoPINNModelParametersView.createInstance()
  File "/Users/ollie/anaconda3/envs/ptychodus/lib/python3.10/site-packages/ptychodus/view/ptychopinn.py", line 56, in createInstance
    layout.addWidget(view.probeScaleSpinBox, 8, 1, 1, 2)
AttributeError: 'PtychoPINNModelParametersView' object has no attribute 'probeScaleSpinBox'

ASSISTANT: The error indicates that there's an attempt to add a widget named `probeScaleSpinBox` to the layout in the `PtychoPINNModelParametersView` class, but this widget does not exist. Based on the context provided earlier, it seems that the correct widget to use here is `probeScaleLineEdit`, which is a `DecimalLineEdit` instance. To resolve this error, the reference to `probeScaleSpinBox` should be updated to `probeScaleLineEdit` in the `createInstance` method of `PtychoPINNModelParametersView`. Here's the necessary change:

```diff
--- ptychodus/view/ptychopinn.py
+++ ptychodus/view/ptychopinn.py
@@ ... @@
-layout.addWidget(view.probeScaleSpinBox, 8, 1, 1, 2)
+layout.addWidget(view.probeScaleLineEdit, 8, 1, 1, 2)
```